// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts       string
	Lessons        string
	Managers       string
	Options        string
	Questions      string
	Roles          string
	Tests          string
	UserFolder     string
	UserTestDetail string
	UserTests      string
	UserWords      string
	Users          string
	WordInFolder   string
	Words          string
	WordsInLessons string
}{
	Accounts:       "accounts",
	Lessons:        "lessons",
	Managers:       "managers",
	Options:        "options",
	Questions:      "questions",
	Roles:          "roles",
	Tests:          "tests",
	UserFolder:     "user_folder",
	UserTestDetail: "user_test_detail",
	UserTests:      "user_tests",
	UserWords:      "user_words",
	Users:          "users",
	WordInFolder:   "word_in_folder",
	Words:          "words",
	WordsInLessons: "words_in_lessons",
}
