// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts        string
	Folders         string
	Lessons         string
	Managers        string
	Options         string
	Questions       string
	Roles           string
	Tests           string
	UserTestDetails string
	UserTests       string
	Users           string
	UsersSavedWords string
	Words           string
	WordsInLessons  string
}{
	Accounts:        "accounts",
	Folders:         "folders",
	Lessons:         "lessons",
	Managers:        "managers",
	Options:         "options",
	Questions:       "questions",
	Roles:           "roles",
	Tests:           "tests",
	UserTestDetails: "user_test_details",
	UserTests:       "user_tests",
	Users:           "users",
	UsersSavedWords: "users_saved_words",
	Words:           "words",
	WordsInLessons:  "words_in_lessons",
}
